services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    user: "1883:1883"
    ports:
      - "1883:1883"      # Default MQTT port for your ESP32
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    environment:
      - TZ=Europe/Ljubljana