services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${MONOLITH_PORT}:${MONOLITH_PORT}"
    volumes:
      - /app/backend/main/src/generated/prisma
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - DEBUG=appName:*
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: plantit_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 3s
      timeout: 3s
      retries: 5

  minio_init:
    image: minio/mc:latest
    container_name: plantit_minio_initializer
    env_file:
      - ./.env
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set my_s3 http://plantit_minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      mc mb --ignore-existing my_s3/plants;
      mc mb --ignore-existing my_s3/recipes;
      mc mb --ignore-existing my_s3/species;
      mc anonymous set download my_s3/plants;
      mc anonymous set download my_s3/recipes;
      mc anonymous set download my_s3/species;
      echo 'Buckets created';
      "
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit-node
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1gb

volumes:
  postgres-data:
  minio_data:
    driver: local
  rabbitmq_data: