management.load_definitions = /etc/rabbitmq/definitions.json

# Настройки логирования (чтобы видеть ошибки прав доступа в логах докера)
log.console = true
log.console.level = info

# Оптимизация памяти (при достижении 40% от лимита контейнера, RabbitMQ притормозит)
vm_memory_high_watermark.relative = 0.4