name: Backend Test

on:
  # push:
  #   branches: [main, dev]
  # pull_request:
  #   branches: [main]
  push:
    branches:
      - 'feature/PLANT-119-testing-github-actions'
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Create .env file from single secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Start entire backend stack
        run: docker compose up -d --build

      - name: Wait for API Gateway / Main Server to be healthy
        run: |
          timeout 300s sh -c 'until curl -s http://localhost:4200/api/species; do sleep 5; done'

      - name: Dump container logs on failure
        if: failure()
        run: |
          docker compose logs
          
      - name: Stop and clean up containers
        if: always()
        run: docker compose down