name: Deploy Docker

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  # push:
  #   branches:
  #     - 'feature/PLANT-119-testing-github-actions'
  workflow_dispatch:

jobs:
  call-backend-tests:
    uses: ./.github/workflows/backend-tests.yml
    secrets: inherit

  call-frontend-tests:
    uses: ./.github/workflows/frontend-tests.yml
    secrets: inherit

  deploy:
    needs: [call-backend-tests, call-frontend-tests]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Docker Login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker containers
        run: |
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/plant-it-stack

      - name: Push docker containers
        run: |
          docker push $DOCKER_USERNAME/plant-it-stack











